### ISSUE TITLE
Missing keyword

### ISSUE THREAD

**Issue by folknor** [phonon/language-galaxy#2]
Hey,

The |trigger| and |actorscope| types are missing from storage.type.galaxy.

Here is the new LotV natives.galaxy: http://hastebin.com/elenaxozeq.java

**Comment by phonon** [comment]
Added "trigger" and "actorscope" keywords.

Also separated out "struct" and "typedef" complex variable keywords from the Blizzard builtin types and added "arrayref", "structref", and "funcref" keywords that were previously missing.
